### ISSUE TITLE
Not able to redirect to app after successful auth verification

### ISSUE THREAD

**Issue by dinabandhuM** [teranetsrl/oauth2_client#37]
I have added the following intent in my App.Manifest file
            `<activity
                    android:name="com.linusu.flutter_web_auth.CallbackActivity">
                    <intent-filter android:label="flutter_web_auth">
                        <action android:name="android.intent.action.VIEW"/>
                        <category android:name="android.intent.category.DEFAULT"/>
                        <category android:name="android.intent.category.BROWSABLE"/>
                        <data android:scheme="https"
                            android:host="loginapp.flutterapp.com"
                            android:pathPrefix="/oauth2redirect"/>
                    </intent-filter>
                </activity>`
request code: 
`Future<void> myOauth2Method() async {
    MyOAuth2Client client = MyOAuth2Client(
      customUriScheme: 'https',
      redirectUri: 'https://loginapp.flutterapp.com/oauth2redirect',
    );

    OAuth2Helper helper = OAuth2Helper(client,
        grantType: OAuth2Helper.AUTHORIZATION_CODE,
        clientId: '*************',
        clientSecret: '************',
        scopes: ['com.intuit.quickbooks.accounting openid email profile'],
        );

   var token = await helper.getToken();

    print('Token: ${token.accessToken}');
  }`
After successful authorization the redirect uri is : https://loginapp.flutterapp.com/oauth2redirect?code=*******
But, instead of launching my app it is trying to open the website.

**Comment by okrad** [comment]
Hi @dinabandhuM, 
you should use a custom scheme for the redirect uri, for example:

```xml
<activity
    android:name="com.linusu.flutter_web_auth.CallbackActivity">
    <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="my.test.app" />
    </intent-filter>
</activity>
```
And then, in your code:

```dart
MyOAuth2Client client = MyOAuth2Client(
      customUriScheme: 'my.test.app',
      redirectUri: 'my.test.app://loginapp.flutterapp.com/oauth2redirect',
    );
```

I just updated the README, hope I made this point clearer!

**Comment by dinabandhuM** [comment]
I understand that. Thanks for updating the README though. But, I am afraid it does not solve my issue. The reason is the custom URI scheme. Like you're setting the custom URI scheme to listen to the Auth code, but many of the Authorization provider (like mine) doesn't allow any other URI scheme except "http" and "https".  In that case, your solution fails to fetch the authCode and request for authToken. 
Kindly, provide me the solution for this.

**Comment by okrad** [comment]
Hi @dinabandhuM, 
to use HTTPS urls you need to define your redirect uri as an App Link. I just updated the README to explain how it can be done.
